---
version: "3.4"
services:
  redis:
    image: redis:alpine
    ports:
    - "6379:6379"
    networks:
    - frontend
  trafficserver:
    build:
      context: .
      target: desenv
      dockerfile: trafficserver.dockerfile
      args:
        ATS_VERSION: 8.0.3
        LUAJIT_VERSION: 2.0.5
        LUAROCKS_VERSION: 3.0.4
    image: cerradotech/trafficserver:latest
    volumes:
    - ${PWD}/config/records.config:/usr/local/etc/trafficserver/records.config
    - ${PWD}/config/remap.config:/opt/ats/etc/trafficserver/remap.config
    - ${PWD}/config/plugin.config:/opt/ats/etc/trafficserver/plugin.config
    - ${PWD}/config/logging.yaml:/opt/ats/etc/trafficserver/logging.yaml
    - ${PWD}/plugins/:/opt/lua-plugins:ro
    ports:
    - "8080:8080"
    networks:
    - frontend
networks:
  frontend:
volumes:
  logs-data:
